[package]
name = "rust-lib-bin"
version = "0.1.0"
authors = ["Julius Oeftiger <joeftiger@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
